### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by chimon2000** [hapipal/hpal#22]
It would be awesome if the CLI could create TypeScript modules.

**Comment by devinivy** [comment]
Technically this is possible using haute-couture amendments with`$literal` manifest examples.  I am interested in bolstering this in the medium-term, particularly because hapi plans to expand its typescript support.  If you play with haute-couture manifest amendments, afterwards please let me know if you have any insights into a nice way to better support typescript scaffolding.

An example of using a haute-couture amendment that integrates with `hpal make`: https://github.com/hapipal/haute-couture/blob/master/API.md#amendment-example
An example of a manifest item that uses `$literal`: https://github.com/hapipal/haute-couture/blob/master/lib/manifest.js#L132-L137
