### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by chimon2000** [hapipal/hpal#23]
It would be awesome if the CLI could create GraphQL Schemas, TypeDefs & Resolvers and work with apollo-server.  Maybe that is out of scope.

**Comment by devinivy** [comment]
I do think it's out of scope at the moment, especially because pal does not have a canonical integration between hapi and GraphQL, however I would like the community to feel enabled to experiment and support such things!  You might have some luck following this example: https://github.com/hapipal/haute-couture/blob/master/API.md#amendment-example
