### ISSUE TITLE
Consider exporting colors

### ISSUE THREAD

**Issue by damusix** [hapipal/hpal#47]
It would be nice to be able to reuse the hpal `colors` functions when writing subcommands for plugins. For example, if I were to want to create the following in `commands.js`:

```js
module.exports = {
    createMigration: {
        command: createMigrations,
        description: [
            'Generates the knex migration.',
            `-d [--directory] to set migrations directory path`,
            `--table to change the table name.`
        ].join('\n\t')
    }
};
```

I would like to be able to extract `bold` or `green` to highlight the options:

```js
const { colors } = require('hpal');
module.exports = {
    createMigration: {
        command: createMigrations,
        description: [
            'Generates the knex migration.',
            `${colors.bold('-d [--directory]')} to set migrations directory path`,
            `${colors.bold('-t [--table]')} to change the table name.`
        ].join('\n\t')
    }
};
```

**Comment by devinivy** [comment]
Yeah, we can certainly do this.  One caveat and one minor consideration:
 - Caveat: I wont be expanding coloring/formatting functionality beyond what is used in hpal.  So it can be expected to remain pretty barebones: bold, red, green, yellow, and grey.
 - Consideration: internally hpal's colors helper is a factory `(enabled) => colors` rather than just `colors` as you have it written above.  For example, this would output green text `colors(true).green('hello')` and this would output plain text `colors(false).green('hello')`.  This allows us to handle the terminal's support for color up front, then write code as though we're coloring text even if it's not supported, so we don't have to handle that condition everywhere.  However, hpal isn't going to do this for you with this helper.  So would you prefer hpal to support this API it uses internally `colors(true).green()` or the way you have it written above _always_ coloring the text `colors.green()`?

Finally, the fourth argument `ctx` object passed to commands already does have a `colors` property that can be used to color text and takes into account the terminal's color support.  We can document this in the readme and make it an officially supported API similarly to `DisplayError`.  But feel free to use it in the interim, as I am very unlikely to change this in the near future.

**Comment by damusix** [comment]
I did see the `ctx.colors` and `ctx.DisplayError` helpers and I am using them. I was hoping to being able to use the colors outside of the `command` function so I can render a bit nicer of a description when running `hpal run --list` without having to install `chalk` or rewrite the colors function. I wouldn't want to alter the configurability of hpal, though. I think it'd be cool only if this could be possible while keeping options in tact.

As far as expanding color and formatting, that is perfectly fine. I am very happy with the basics. Just want a little lipstick on my options descriptions 😝 

Would it be possible to allow the commands configuration object to be a function that is passed context and returns an object?

```js
module.exports = (ctx) => ({
    createMigration: {
        command: createMigrations,
        description: [
            'Generates the knex migration.',
            `${ctx.colors.bold('-d [--directory]')} to set migrations directory path`,
            `${ctx.colors.bold('-t [--table]')} to change the table name.`
        ].join('\n\t')
    }
});
```

Maybe description can be a function that returns a string:

```js

module.exports = {
    createMigration: {
        command: createMigrations,
        description: (ctx) => [
            'Generates the knex migration.',
            `${ctx.colors.bold('-d [--directory]')} to set migrations directory path`,
            `${ctx.colors.bold('-t [--table]')} to change the table name.`
        ].join('\n\t')
    }
};
```

**Comment by devinivy** [comment]
I think that last idea you just threw out is really cohesive with everything else currently going on with hpal 👍 Take a look at #48, hopefully that will do the trick.
